=== bhuvi3/stajistics/stajistics-snapshot-xml/src/main/resources/StatisticsSnapshot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 Copyright 2009 The Stajistics Project

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ss="http://www.stajistics.org/StatisticsSnapshot/"
  xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0"
  targetNamespace="http://www.stajistics.org/StatisticsSnapshot/">
  <element name="snapshot">
    <complexType>
      <sequence>
        <element name="schemaVersion" type="string" maxOccurs="1"
          minOccurs="1">
        </element>
        <element name="stajisticsVersion" type="string"
          maxOccurs="1" minOccurs="1">
        </element>
        <element name="timeSpan" maxOccurs="1" minOccurs="1">
          <complexType>
            <sequence>
              <element name="start" type="dateTime" maxOccurs="1"
                minOccurs="1">
              </element>
              <element name="end" type="dateTime" maxOccurs="1"
                minOccurs="1">
              </element>
            </sequence>
          </complexType>
        </element>
        <element name="environment" maxOccurs="1" minOccurs="1">
          <complexType>
            <sequence>
              <element name="system" maxOccurs="1" minOccurs="1">
                <complexType>
                  <sequence>
                    <element name="hostName" type="string"
                      maxOccurs="1" minOccurs="1">
                    </element>
                    <element name="properties" type="ss:propertiesType"
                      maxOccurs="1" minOccurs="1">
                    </element>
                  </sequence>
                </complexType>
              </element>
              <element name="application" maxOccurs="1"
                minOccurs="1">
                <complexType>
                  <sequence>
                    <element name="properties" type="string"
                      maxOccurs="1" minOccurs="0">
                    </element>
                  </sequence>
                </complexType>
              </element>
            </sequence>
          </complexType>
        </element>
        <element name="activityLog" maxOccurs="1" minOccurs="1">
          <complexType>
            <sequence>
              <element name="logEntry" maxOccurs="unbounded"
                minOccurs="0">
                <complexType>
                  <sequence>
                    <element name="timeStamp" type="dateTime"
                      maxOccurs="1" minOccurs="1">
                    </element>
                    <element name="message" type="string"
                      maxOccurs="1" minOccurs="1">
                    </element>
                  </sequence>
                </complexType>
              </element>
            </sequence>
          </complexType>
        </element>
        <element name="sessions" maxOccurs="1" minOccurs="1">
          <complexType>
            <sequence>
              <element name="session" maxOccurs="unbounded"
                minOccurs="0">
                <complexType>
                  <sequence>
                    <element name="key" type="ss:keyType"
                      maxOccurs="1" minOccurs="1">
                    </element>
                    <element name="trackerFactory" type="string"
                      maxOccurs="1" minOccurs="1">
                    </element>
                    <element name="sessionFactory" type="string"
                      maxOccurs="1" minOccurs="1">
                    </element>
                    <element name="dataRecorders" maxOccurs="1"
                      minOccurs="0">
                      <complexType>
                        <sequence>
                          <element name="dataRecorder" type="string"
                            maxOccurs="unbounded" minOccurs="0">
                          </element>
                        </sequence>
                      </complexType>
                    </element>
                    <element name="unit" type="string"
                      maxOccurs="1" minOccurs="1">
                    </element>
                    <element name="dataSet" type="ss:dataSetType"
                      maxOccurs="1" minOccurs="1">
                    </element>
                  </sequence>
                </complexType>
              </element>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
  <complexType name="propertiesType">
    <sequence>
      <element name="property" type="ss:propertyType" maxOccurs="unbounded"
        minOccurs="1"></element>
    </sequence>
  </complexType>
  <complexType name="propertyType">
    <sequence>
      <element name="name" type="string" maxOccurs="1"
        minOccurs="1"></element>
      <element name="value" type="string" maxOccurs="1"
        minOccurs="1"></element>
    </sequence>
  </complexType>
  <complexType name="keyType">
    <sequence>
      <element name="name" type="string" maxOccurs="1"
        minOccurs="1"></element>
      <element name="attributes" type="ss:attributesType"
        maxOccurs="1" minOccurs="0"></element>
    </sequence>
  </complexType>
  <complexType name="attributesType">
    <sequence>
      <element name="attribute" type="ss:attributeType"
        maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>
  <complexType name="attributeType">
    <sequence>
      <element name="name" type="string" maxOccurs="1"
        minOccurs="1">
      </element>
      <element name="value" type="string" maxOccurs="1"
        minOccurs="1">
      </element>
      <element name="type" type="string" maxOccurs="1"
        minOccurs="0"></element>
    </sequence>
  </complexType>
  <complexType name="dataSetType">
    <sequence>
      <element name="meta" type="ss:attributesType" maxOccurs="1"
        minOccurs="0">
      </element>
      <element name="field" type="ss:fieldType" maxOccurs="unbounded"
        minOccurs="0">
      </element>
    </sequence>
  </complexType>
  <complexType name="fieldType">
    <sequence>
      <element name="name" type="string" maxOccurs="1"
        minOccurs="1">
      </element>
      <element name="value" type="string" maxOccurs="1" minOccurs="1">
      </element>
      <element name="type" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="meta" type="ss:attributesType" maxOccurs="1" minOccurs="0">
      </element>
    </sequence>
  </complexType>
</schema>

=== bhuvi3/stajistics/stajistics-snapshot-xml/target/classes/TestStatisticsSnapshot.xml
<?xml version="1.0" encoding="UTF-8"?>
<ss:snapshot xmlns:ss="http://www.stajistics.org/StatisticsSnapshot/" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:schemaLocation="http://www.stajistics.org/StatisticsSnapshot/ StatisticsSnapshot.xsd ">
  <schemaVersion>schemaVersion</schemaVersion>
  <timeStamp>2001-12-31T12:00:00</timeStamp>
  <guid>35235235</guid> <!-- a hash of the env, config? -->
  <generation>4</generation> <!-- Store the start/end timestamps of the active period? -->
  <environment>
    <system>
      <systemName>localhost</systemName>
      <properties>
        <property>
          <name>java.class.path</name>
          <value>.</value>
        </property>
      </properties>
    </system>
    <application>
      <name>Wicked</name>
    </application>
  </environment>
  <configurations>
    <configuration>
      <key><name>test</name></key>
      <trackerFactory>asdf</trackerFactory>
      <sessionFactory>asdf</sessionFactory>
      <unit>ms</unit>
      <description>test</description>
    </configuration>
  </configurations>
  <sessions>
    <session>
      <key><name>test</name></key>
      <dataSet>
        <field>
          <name>hits</name>
          <value>3</value>
          <meta>
            <attribute>
              <name>type</name>
              <value>int</value>
            </attribute>
          </meta>
        </field>
      </dataSet>
    </session>
  </sessions>
</ss:snapshot>
